builds:
  - binary: oscxyz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64 # for new macs
    flags:
      - -mod=vendor
universal_binaries:
  # for macs... create one binary instead of two
  - replace: true
release:
  # if version number has a dash or plus it won't be distributed
  prerelease: auto
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: darwin
      format: zip
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
